### ISSUE TITLE
usage with docker

### ISSUE THREAD

**Issue by ratio91** [SvenSommer/darksky2influxdb#2]
Hi, 
I run a dockerized TIG stack on my RaspberryPi.
I could now just install node.js as follow your instructions, but I would prefer to have everything in docker.
Anything I have to be careful of when dockerizing your service?
Or could you maybe release a docker image of your script, which uses environment variables as parameters (e.g. InfluxDB host, etc)? 

that would be awesome! thank you!

**Comment by SvenSommer** [comment]
Sorry, was not aware of this issue. Please reopen, if this is still an topic
