### ISSUE TITLE
Incorrect temperatures pushed to InfluxDB?

### ISSUE THREAD

**Issue by sorentorp** [SvenSommer/darksky2influxdb#3]
Hi SvenSommer

I just stumbelled on your little neat project! But the readings that I'm getting out, seems to be off...

Here is the raw pull from Dark Sky, and the temperatures seems to be right here.
https://api.darksky.net/forecast/<API-KEY>/56.1191,10.162289

Dark Sky map for the area
![2018-11-15 08_45_39-dark sky maps google chrome](https://user-images.githubusercontent.com/4117997/48537789-e47cb180-e8b2-11e8-8b49-8fdaedc14938.png)

My Grafana showing temperatures around 20 degrees C, not 8 degrees C...
![2018-11-15 08_45_02-grafana - weather - forecast google chrome](https://user-images.githubusercontent.com/4117997/48537783-df1f6700-e8b2-11e8-9ac5-74654f768ae1.png)

Hope you can help out.

**Comment by SvenSommer** [comment]
Sorry, was not aware of this issue. Please reopen, if this is still an topic
