### ISSUE TITLE
darsky API end of service end of march 23

### ISSUE THREAD

**Issue by dmqgit** [SvenSommer/darksky2influxdb#6]
Hi,

thanks for the great dashboard / importer. I am using it for years now and I do not want to miss it. As you know, dark sky will stop to work on the 31th of march 23. Do you have plans to migrate to openweathermap or DWD? If not I will probably look to build something myself (but not with node.js). It would be helpful to know if you maybe have plans :)

Thanks and happy new year.

dmq

**Comment by SvenSommer** [comment]
Hey dmg,
Probably not able to do it myself. If someone is able to provide a solution as pull request, I will be happy to merge this.
